networks:
  mini-trello-net:
    name: mini-trello-net
    driver: bridge

volumes:
  postgres_data:
    name: mini-trello-postgres-data
  redis_data:
    name: mini-trello-redis-data

services:
  postgres:
    image: postgres:15
    container_name: mini-trello-postgres
    restart: unless-stopped

    networks:
      - mini-trello-net

    ports:
      - "${DATABASE_PORT}:5432"

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - mini-trello-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - mini-trello-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
    ports:
      - '5000:5000'
      - '5044:5044'
    volumes:
      - ./src/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - mini-trello-net

  redis:
    image: redis:8-alpine
    container_name: mini-trello-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
